
package atm_p.BankingPlatform;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.ui.FlatListCellBorder;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JComponent;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.EtchedBorder;
import javax.swing.border.LineBorder;
import javax.swing.border.MatteBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import splashscreen.LogoIcon;

/**
 *
 * @author user
 */
public class accountOpaningForm extends javax.swing.JFrame {
    accountOpaningForm openedForm;
    UserProfileData userProfileData;
    private boolean isImageUploaded=false;
    
    int screenW;
    int screenH;

    
    public accountOpaningForm() {
       
        initComponents();
                

          Toolkit kit=Toolkit.getDefaultToolkit();
       Dimension screen= kit.getScreenSize();
        setSize(screenW=screen.width,screenH=screen.height);
        pack();
//        new NewJDialog(null, true).setVisible(true);
    }
    public accountOpaningForm(UserProfileData userProfileData) {
        
        this.userProfileData=userProfileData;
        initComponents();
          Toolkit kit=Toolkit.getDefaultToolkit();
          new LogoIcon().setLogo(this);
       Dimension screen= kit.getScreenSize();
        setSize(screenW=screen.width,screenH=screen.height);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        minimizeL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        declareBox = new javax.swing.JCheckBox();
        submitBt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        publicBt = new javax.swing.JRadioButton();
        adminBt = new javax.swing.JRadioButton();
        noteL = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        CustomerUID = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jComboBox11 = new javax.swing.JComboBox<>();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        nomini_name = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        nomini_relation = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        nomini_uid = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        nomini_checkBox = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/userDitailbackGround.png"))); // NOI18N
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1536, 864);

        jPanel1.setOpaque(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-close-32 (2).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        minimizeL.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        minimizeL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-subtract-32.png"))); // NOI18N
        minimizeL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText(" Personal Details");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Customer Type*");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel5.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Name*");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel4.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Father Name/Mother Name*");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Date of Birth*");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Nationality*");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel8.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Marital Status*");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel9.setOpaque(true);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" UID*");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel10.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText(" Corresponding / Paermanenet Address");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" State/U.T.*");
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel12.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" Permanent Address*");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel13.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" Mobile Number*");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel14.setOpaque(true);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" Email Address");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel15.setOpaque(true);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText(" Others");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(" Account Type*");
        jLabel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel20.setOpaque(true);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(" Card /Check Book Facilities");
        jLabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel22.setOpaque(true);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(" Nomination Facility");
        jLabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel21.setOpaque(true);

        jLabel18.setText("I hereby declare the above-listed particulars of  informati");

        declareBox.setForeground(new java.awt.Color(255, 255, 255));
        declareBox.setText("jCheckBox1");
        declareBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declareBoxActionPerformed(evt);
            }
        });

        submitBt.setBackground(new java.awt.Color(0, 51, 51));
        submitBt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submitBt.setForeground(new java.awt.Color(255, 255, 255));
        submitBt.setText("SUBMIT");
        submitBt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        submitBt.setEnabled(false);
        submitBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitBtMouseExited(evt);
            }
        });
        submitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(25, 31, 38));
        jPanel2.setLayout(null);

        publicBt.setBackground(new java.awt.Color(25, 31, 38));
        publicBt.setForeground(new java.awt.Color(255, 255, 255));
        publicBt.setText("Public");
        publicBt.setBorder(null);
        publicBt.setBorderPainted(true);
        publicBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-toggle-off-22 (1).png"))); // NOI18N
        publicBt.setOpaque(true);
        publicBt.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-toggle-on-22.png"))); // NOI18N
        publicBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicBtActionPerformed(evt);
            }
        });
        jPanel2.add(publicBt);
        publicBt.setBounds(10, 20, 90, 30);

        adminBt.setBackground(new java.awt.Color(25, 31, 38));
        adminBt.setForeground(new java.awt.Color(255, 255, 255));
        adminBt.setText("New ADMIN");
        adminBt.setBorder(null);
        adminBt.setBorderPainted(true);
        adminBt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adminBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-toggle-off-22 (1).png"))); // NOI18N
        adminBt.setOpaque(true);
        adminBt.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-toggle-on-22.png"))); // NOI18N
        adminBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminBtMouseExited(evt);
            }
        });
        adminBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtActionPerformed(evt);
            }
        });
        jPanel2.add(adminBt);
        adminBt.setBounds(120, 20, 90, 30);

        noteL.setBackground(new java.awt.Color(255, 255, 255));
        noteL.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        noteL.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        noteL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noteL.setText("You can Just apply to be a new ADMIN !");
        noteL.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, java.awt.Color.white));
        noteL.setVisible(false);
        jPanel2.add(noteL);
        noteL.setBounds(220, 20, 250, 30);

        jComboBox1.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Mrs." }));
        jComboBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(10, 60, 84, 30);

        jTextField1.setBackground(new java.awt.Color(0, 51, 51));
        jTextField1.setForeground(new java.awt.Color(140, 140, 140));
        jTextField1.setText("First Name");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(120, 60, 215, 30);

        jTextField2.setBackground(new java.awt.Color(0, 51, 51));
        jTextField2.setForeground(new java.awt.Color(140, 140, 140));
        jTextField2.setText("Last Name");
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(360, 60, 215, 30);

        jComboBox2.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Mrs." }));
        jComboBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(10, 100, 84, 30);

        jTextField3.setBackground(new java.awt.Color(0, 51, 51));
        jTextField3.setForeground(new java.awt.Color(140, 140, 140));
        jTextField3.setText("Full Name");
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField3);
        jTextField3.setBounds(120, 100, 215, 30);

        jComboBox3.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox3.setForeground(new java.awt.Color(140, 140, 140));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(10, 140, 84, 30);

        jComboBox4.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox4.setForeground(new java.awt.Color(140, 140, 140));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jComboBox4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox4);
        jComboBox4.setBounds(120, 140, 72, 30);

        jComboBox5.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox5.setForeground(new java.awt.Color(140, 140, 140));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1998", "1999", "2000", "2001" }));
        jComboBox5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox5);
        jComboBox5.setBounds(200, 140, 62, 30);

        jLabel17.setBackground(new java.awt.Color(153, 153, 153));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gender*");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(300, 140, 68, 30);

        jRadioButton3.setBackground(new java.awt.Color(25, 31, 38));
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Male");
        jRadioButton3.setBorderPainted(true);
        jRadioButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-toggle-off-22 (1).png"))); // NOI18N
        jRadioButton3.setOpaque(true);
        jRadioButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-toggle-on-22.png"))); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(370, 140, 80, 30);

        jRadioButton4.setBackground(new java.awt.Color(25, 31, 38));
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Female");
        jRadioButton4.setBorderPainted(true);
        jRadioButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-toggle-off-22 (1).png"))); // NOI18N
        jRadioButton4.setOpaque(true);
        jRadioButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-toggle-on-22.png"))); // NOI18N
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton4);
        jRadioButton4.setBounds(460, 140, 63, 30);

        jComboBox6.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox6.setForeground(new java.awt.Color(140, 140, 140));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select__", "Indian" }));
        jComboBox6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox6);
        jComboBox6.setBounds(10, 180, 84, 30);

        jLabel19.setBackground(new java.awt.Color(153, 153, 153));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Religion");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(300, 180, 68, 30);

        jComboBox9.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox9.setForeground(new java.awt.Color(140, 140, 140));
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select__", "Hindu", "Muslim", "Sikh", "Christian" }));
        jComboBox9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox9);
        jComboBox9.setBounds(370, 180, 81, 30);

        jComboBox10.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox10.setForeground(new java.awt.Color(140, 140, 140));
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select__", "Single", "Married", "Widowed", "Divorced", "Separated" }));
        jComboBox10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox10);
        jComboBox10.setBounds(10, 220, 86, 30);

        jPanel5.setBackground(new java.awt.Color(25, 31, 38));

        jLabel31.setBackground(new java.awt.Color(25, 31, 38));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/uploadimage.png"))); // NOI18N
        jLabel31.setOpaque(true);
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel31MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(767, -14, 260, 220);

        CustomerUID.setBackground(new java.awt.Color(0, 51, 51));
        CustomerUID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        CustomerUID.setForeground(new java.awt.Color(255, 255, 255));
        try {
            CustomerUID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CustomerUID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CustomerUID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CustomerUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerUIDActionPerformed(evt);
            }
        });
        jPanel2.add(CustomerUID);
        CustomerUID.setBounds(10, 260, 158, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 50, 780, 0);

        jPanel3.setBackground(new java.awt.Color(25, 31, 38));

        jComboBox7.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox7.setForeground(new java.awt.Color(140, 140, 140));
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "__Select__", "Rajasthan" }));
        jComboBox7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("PIN*");

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("City*");

        jComboBox8.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox8.setForeground(new java.awt.Color(140, 140, 140));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "__Select__", "Bharatpur" }));
        jComboBox8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(0, 51, 51));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField4.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(0, 51, 51));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField5.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField7.setBackground(new java.awt.Color(0, 51, 51));
        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField7.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });

        jTextField8.setBackground(new java.awt.Color(0, 51, 51));
        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(140, 140, 140));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField8.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(683, 683, 683))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(25, 31, 38));

        jComboBox11.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox11.setForeground(new java.awt.Color(140, 140, 140));
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "__Select__", "Savings account", "Salary account", "Fixed deposit account", "Recurring deposit account", "NRI accounts." }));
        jComboBox11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox11ActionPerformed(evt);
            }
        });

        jCheckBox2.setBackground(new java.awt.Color(25, 31, 38));
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Creadit Card");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setBackground(new java.awt.Color(25, 31, 38));
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Debit Card");

        jCheckBox4.setBackground(new java.awt.Color(25, 31, 38));
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Cheque Book");

        jLabel26.setBackground(java.awt.Color.black);
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Name");

        nomini_name.setBackground(new java.awt.Color(0, 51, 51));
        nomini_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        nomini_name.setForeground(new java.awt.Color(255, 255, 255));
        nomini_name.setCaretColor(new java.awt.Color(255, 255, 255));
        nomini_name.setEnabled(false);
        nomini_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomini_nameActionPerformed(evt);
            }
        });

        jLabel27.setBackground(java.awt.Color.black);
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Relation");

        nomini_relation.setBackground(new java.awt.Color(0, 51, 51));
        nomini_relation.setForeground(new java.awt.Color(140, 140, 140));
        nomini_relation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "__select__", "Husband", "Wife", "Son", "Daughter", "Brother", "Sister", "Other" }));
        nomini_relation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        nomini_relation.setEnabled(false);
        nomini_relation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomini_relationActionPerformed(evt);
            }
        });

        jLabel28.setBackground(java.awt.Color.black);
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("UID");

        nomini_uid.setBackground(new java.awt.Color(0, 51, 51));
        nomini_uid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        nomini_uid.setForeground(new java.awt.Color(255, 255, 255));
        try {
            nomini_uid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nomini_uid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomini_uid.setToolTipText("");
        nomini_uid.setCaretColor(new java.awt.Color(255, 255, 255));
        nomini_uid.setEnabled(false);
        nomini_uid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nomini_uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomini_uidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(nomini_name, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomini_relation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomini_uid, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addGap(807, 807, 807))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomini_uid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomini_relation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomini_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("on and evidence are true to the best of my knowledge.");

        jLabel29.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("ACCOUNT OPENING FORM");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-account-32.png"))); // NOI18N

        nomini_checkBox.setBackground(new java.awt.Color(255, 255, 255));
        nomini_checkBox.setForeground(new java.awt.Color(255, 255, 255));
        nomini_checkBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nomini_checkBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nomini_checkBoxMouseExited(evt);
            }
        });
        nomini_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomini_checkBoxBoxActionPerformed(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(0, 0, 0));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Check me for nomini !");
        jLabel32.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, java.awt.Color.white));
        jLabel32.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(nomini_checkBox)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(declareBox, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel18)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(minimizeL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nomini_checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel32))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(declareBox)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel25)
                            .addComponent(submitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jPanel1);
        jPanel1.setBounds(-10, 0, 1536, 920);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLMouseClicked
        setState(LoginPage.ICONIFIED);//Minimize the window Iconfied is known as minimization process
    }//GEN-LAST:event_minimizeLMouseClicked

    private void declareBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declareBoxActionPerformed
        if(declareBox.isSelected())submitBt.setEnabled(true);
        else{submitBt.setEnabled(false);}
    }//GEN-LAST:event_declareBoxActionPerformed

    private void submitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtActionPerformed
        

//CustomeType
        if(publicBt.isSelected()==false && adminBt.isSelected()==false){
          
           Warning.warning(publicBt, false);
        }else{
            Warning.removeWarning(publicBt,"lightBlack");
            userProfileData.CustomerType=(publicBt.isSelected()==true)?"Public":"Admin";
        }
       
//AccountType        
        if(isSelected(jComboBox11)){
            Warning.removeWarning(jComboBox11,"black");
            userProfileData.AccountType= jComboBox11.getSelectedItem().toString();
        }
        else{Warning.warning(jComboBox11, false);
        }
        
//Religion
        if(isSelected(jComboBox9)){
            Warning.removeWarning(jComboBox9,"black");
            userProfileData.Religion= jComboBox9.getSelectedItem().toString();
        }
        else{Warning.warning(jComboBox9, false);
        }
        
// City        
        if(isSelected(jComboBox8)){
            Warning.removeWarning(jComboBox8,"black");
            userProfileData.City = jComboBox8.getSelectedItem().toString();
        }
        else{Warning.warning(jComboBox8, false);}
        
// Pin  
        if(!jTextField8.getText().isBlank()){
            Warning.removeWarning(jTextField8,"black"); 
            userProfileData.PinCode=jTextField8.getText();
        }else{Warning.warning(jTextField8, false);}
        
// State        
        if(isSelected(jComboBox7)&&jComboBox7.getForeground().equals(Color.white)){
            Warning.removeWarning(jComboBox7,"black");
            userProfileData.State = jComboBox7.getSelectedItem().toString();
        }
        else{Warning.warning(jComboBox7, false);}        

//Date of birth        
        if(isSelected(jComboBox3)){
            Warning.removeWarning(jComboBox3,"black");
            if(isSelected(jComboBox4)){
                Warning.removeWarning(jComboBox4,"black");
                if(isSelected(jComboBox5)){
                    Warning.removeWarning(jComboBox5,"black");
                    userProfileData.DateOfBirth=jComboBox3.getSelectedItem()+"/"+jComboBox4.getSelectedItem()+"/"+jComboBox5.getSelectedItem();
                }else{Warning.warning(jComboBox5, false);}
            }else{Warning.warning(jComboBox4, false);}
        }else{Warning.warning(jComboBox3, false);}
        
//Fathers/mother name
      if(!jTextField3.getText().isBlank()&&jTextField3.getForeground()==Color.white){
                 Warning.removeWarning(jTextField3,"black");
                 userProfileData.ParentsName=jComboBox2.getSelectedItem()+" "+jTextField3.getText();
             }else{Warning.warning(jTextField3, false);}
        
//Customer Name
         if(!jTextField1.getText().isBlank()&&jTextField1.getForeground()==Color.white){
             Warning.removeWarning(jTextField1,"black");
             if(!jTextField2.getText().isBlank()&&jTextField2.getForeground()==Color.white){
                 Warning.removeWarning(jTextField2,"black");
                 userProfileData.CustomerName=jComboBox1.getSelectedItem()+" "+jTextField1.getText()+" "+jTextField2.getText();
             }else{Warning.warning(jTextField2, false);}
         }else{Warning.warning(jTextField1, false);}
         
//CustomerUId NUmber
        if(CustomerUID.isEditValid()){
            Warning.removeWarning(CustomerUID,"black");
        }else{Warning.warning(CustomerUID, false);}
// phn number
        if(!jTextField7.getText().isBlank()){
            Warning.removeWarning(jTextField7,"black"); 
            userProfileData.MobileNumber=jTextField7.getText();
        }else{Warning.warning(jTextField7, false);}
        
//Gender
        if(jRadioButton3.isSelected()==false && jRadioButton4.isSelected()==false){
           Warning.warning(jLabel17, false);
        }else{
            Warning.removeWarning(jLabel17,"lightBlack");
            userProfileData.Gender=(jRadioButton3.isSelected()==true)?"Male":"Female";
        }
        
//Material Status
        if(isSelected(jComboBox10)){
            Warning.removeWarning(jComboBox10,"black");
            userProfileData.MaterialStatus=jComboBox10.getSelectedItem().toString();
        }else{Warning.warning(jComboBox10, false);}
        

//Nationallity
        if(isSelected(jComboBox6)){
            Warning.removeWarning(jComboBox6,"black");
            userProfileData.Nationality=jComboBox6.getSelectedItem().toString();
        }else{Warning.warning(jComboBox6, false);}
        
//NOmini
        if(nomini_checkBox.isSelected()){
            if(!nomini_name.getText().isBlank()){
                 Warning.removeWarning(nomini_name,"black ");
                if(isSelected(nomini_relation)==true){
                     Warning.removeWarning(nomini_relation,"black");
                    if(nomini_uid.isEditValid()){
                          Warning.removeWarning(nomini_uid,"black");
                         userProfileData.Nomini=nomini_checkBox.isSelected();
                         userProfileData.NominiName=nomini_name.getText();
                         userProfileData.NominiRelation=nomini_relation.getSelectedItem().toString();
                         userProfileData.NominiUID = nomini_uid.getText();
                    }else{Warning.warning(nomini_uid, false);}
                }else{Warning.warning(nomini_relation, false);}
            }else{Warning.warning(nomini_name, false);}
        }
        System.out.println(nomini_uid.getText().length());
//address
        if(!jTextField4.getText().isBlank()){
            Warning.removeWarning(jTextField4,"black");
            userProfileData.PermanentAddress=jTextField4.getText();
        }else{Warning.warning(jTextField4, false);}
        
        userProfileData.ChequeBook=jCheckBox4.isSelected();
        userProfileData.CreaditCard = jCheckBox2.isSelected();
        userProfileData.DebitCard=jCheckBox3.isSelected();
        userProfileData.EmailAddress=jTextField5.getText();
        
        userProfileData.UID=CustomerUID.getText();
        
//Image
       if(!isImageUploaded){
           jLabel31.setBorder(new LineBorder(Color.red));
       }
       if(!isWarningVisible()){
           //save in data base
           
           java.awt.EventQueue.invokeLater(new Runnable(){
               public void run(){
                   try{
                   new BotDialog(userProfileData,openedForm).setVisible(true);
                   }catch(Exception e){
                       e.printStackTrace();
                   }
               }
           });
           
       }else{
           Toolkit.getDefaultToolkit().beep();
       }
       
    }//GEN-LAST:event_submitBtActionPerformed
   
    private boolean isSelected(JComboBox t){
        return (t.getSelectedIndex()>0);
    }
    private boolean isWarn(JComponent j){
        return (((LineBorder)j.getBorder()).getLineColor()==Color.red);
    }
    private boolean isWarningVisible(){
        if(isWarn(publicBt)||isWarn(jComboBox8)||isWarn(jComboBox7)||isWarn(jComboBox6)||isWarn(jComboBox10)||isWarn(jComboBox3)
                ||isWarn(jComboBox4)||isWarn(jComboBox5)||isWarn(jTextField1)||isWarn(jTextField2)||isWarn(jTextField3)||isWarn(jTextField4)||isWarn(jComboBox9)
                ||isWarn(CustomerUID)||isWarn(jTextField7)||isWarn(jTextField8)||isWarn(jLabel17)
                ||!isImageUploaded){
                        return true;}
            if(jPanel4.isVisible()){
                return isWarn(jComboBox11);
            }
            
            if(nomini_checkBox.isSelected()){
                return (isWarn(nomini_name)||isWarn(nomini_relation)||isWarn(nomini_uid));
            }
            return false;
    }
    private void publicBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicBtActionPerformed
        if(publicBt.isSelected()){
            adminBt.setSelected(false);
            submitBt.setText("SUBMIT");
             jComboBox11.setEnabled(true);
            jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox4.setEnabled(true);
            nomini_checkBox.setEnabled(true);
           jPanel4.setVisible(true);
        }

    }//GEN-LAST:event_publicBtActionPerformed

    private void adminBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBtMouseEntered
        noteL.setVisible(true);
    }//GEN-LAST:event_adminBtMouseEntered

    private void adminBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBtMouseExited
        noteL.setVisible(false);
    }//GEN-LAST:event_adminBtMouseExited

    private void adminBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtActionPerformed
        if(adminBt.isSelected()){
            publicBt.setSelected(false);
            submitBt.setText("APPLY");
            jComboBox11.setEnabled(false);
            jCheckBox2.setEnabled(false);
            jCheckBox3.setEnabled(false);
            jCheckBox4.setEnabled(false);
            nomini_checkBox.setEnabled(false);
            jLabel32.setText("Not allowed for admin account");
            jPanel4.setVisible(false);
            nomini_checkBox.setSelected(false);
        }
        else{submitBt.setText("SUBMIT");
        jPanel4.setVisible(true);}

    }//GEN-LAST:event_adminBtActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
         if(jComboBox4.getSelectedIndex()>0){jComboBox4.setForeground(Color.white);}
       else{jComboBox4.setForeground(new Color(140,140,140));}
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if(jRadioButton3.isSelected()){
            jRadioButton4.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        if(jRadioButton4.isSelected()){
            jRadioButton3.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        if(jComboBox6.getSelectedIndex()>0){jComboBox6.setForeground(Color.white);}
       else{jComboBox6.setForeground(new Color(140,140,140));}
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        if(jComboBox9.getSelectedIndex()>0){jComboBox9.setForeground(Color.white);}
       else{jComboBox9.setForeground(new Color(140,140,140));}
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void nomini_checkBoxBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomini_checkBoxBoxActionPerformed
        if(!nomini_checkBox.isSelected()){ 
            Warning.removeWarning(nomini_name, "white");//for removing the warning when we checkd end get error and then suddenly unchecked in that case it will remove the red line
            Warning.removeWarning(nomini_relation, "white");
            Warning.removeWarning(nomini_uid, "white");
            nomini_name.setEnabled(false);
            nomini_relation.setEnabled(false);
            nomini_uid.setEnabled(false);}
        else{nomini_relation.setEnabled(true);
            nomini_uid.setEnabled(true);
            nomini_name.setEnabled(true);}

    }//GEN-LAST:event_nomini_checkBoxBoxActionPerformed

    private void nomini_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomini_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomini_nameActionPerformed

    private void nomini_relationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomini_relationActionPerformed
       if(nomini_relation.getSelectedIndex()>0){nomini_relation.setForeground(Color.white);}
       else{nomini_relation.setForeground(new Color(140,140,140));}
    }//GEN-LAST:event_nomini_relationActionPerformed

    private void nomini_uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomini_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomini_uidActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
//      jComboBox1.addItemListener(new ItemListe);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void minimizeLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLMouseEntered
      minimizeL.setBorder(new EtchedBorder(Color.white, Color.white));
    }//GEN-LAST:event_minimizeLMouseEntered

    private void minimizeLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLMouseExited
        minimizeL.setBorder(new EtchedBorder(Color.black, Color.black));
    }//GEN-LAST:event_minimizeLMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setBorder(new EtchedBorder(Color.white, Color.white));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
         jLabel2.setBorder(new EtchedBorder(Color.black , Color.black));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseEntered
        jLabel31.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Upload", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jLabel31MouseEntered

    private void jLabel31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseExited
        jLabel31.setBorder(new FlatListCellBorder.Default());
    }//GEN-LAST:event_jLabel31MouseExited

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        try {
            JFileChooser fc = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG/PNG File", "jpg","jpeg","png");
            fc.addChoosableFileFilter(filter);
            fc.showOpenDialog(null);
            File fs = fc.getSelectedFile();
            
            if(fs==null){
                JOptionPane.showMessageDialog(null, "File is not found !", "Error", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/atm_p/pictures/icons8-error-16.png")));
            }
            else{
                String extension = fs.getPath().toString().toLowerCase();
                if(extension.endsWith(".jpg")||extension.endsWith(".png")){
                    UserProfileData.imageExtension = extension(fs.getPath().toString().toLowerCase());
                   
                   ImageIcon imageicon = new ImageIcon(fs.getAbsolutePath());
                   long size = fs.length();
                    if(size<16777216){
                    isImageUploaded=true;
                    java.awt.Image image = imageicon.getImage();
                    java.awt.Image scaledImage = image.getScaledInstance(jLabel31.getWidth(), jLabel31.getHeight(), java.awt.Image.SCALE_AREA_AVERAGING);
                    jLabel31.setIcon(new ImageIcon(scaledImage));
                    userProfileData.UserImage = new FileInputStream(fs);//this is used when we save it in database;
                    }
                     else{
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(null, "Size must be smaller then 16MB", "Error", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/atm_p/pictures/icons8-error-16.png")));
                    }
                }
                else{
                    Toolkit.getDefaultToolkit().beep();
                     JOptionPane.showMessageDialog(null, "File formate must be JPG/JPEG/PNG !", "Error", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/atm_p/pictures/icons8-error-16.png")));
                }
              
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel31MouseClicked
    private String extension(String ApsolutePath){
        StringBuilder sb = new StringBuilder(ApsolutePath);
        sb=sb.reverse();
        String s = sb.toString();
        StringBuilder ss = new StringBuilder(s.substring(0, 3));
        return ss.reverse().toString();
    }
    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
         if(!(jTextField1.getForeground().equals(Color.white))){
            jTextField1.setText("");
            jTextField1.setForeground(Color.white); 
        }  
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
       if(!(jTextField2.getForeground().equals(Color.white))){
            jTextField2.setText("");
            jTextField2.setForeground(Color.white); 
        }  
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
         if(!(jTextField3.getForeground().equals(Color.white))){
            jTextField3.setText("");
            jTextField3.setForeground(Color.white); 
        }
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jComboBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox11ActionPerformed
       if(jComboBox11.getSelectedIndex()>0){jComboBox11.setForeground(Color.white);}
       else{jComboBox11.setForeground(new Color(140,140,140));}
    }//GEN-LAST:event_jComboBox11ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        if(jComboBox8.getSelectedIndex()>0){jComboBox8.setForeground(Color.white);}
       else{jComboBox8.setForeground(new Color(140,140,140));}
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
       if(jComboBox7.getSelectedIndex()>0){jComboBox7.setForeground(Color.white);}
       else{jComboBox7.setForeground(new Color(140,140,140));}
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
         if(jComboBox3.getSelectedIndex()>0){jComboBox3.setForeground(Color.white);}
       else{jComboBox3.setForeground(new Color(140,140,140));}
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
         if(jComboBox5.getSelectedIndex()>0){jComboBox5.setForeground(Color.white);}
       else{jComboBox5.setForeground(new Color(140,140,140));}
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        if(jComboBox10.getSelectedIndex()>0){jComboBox10.setForeground(Color.white);}
       else{jComboBox10.setForeground(new Color(140,140,140));}
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusGained
        if(!(jTextField8.getForeground().equals(Color.white))){
            jTextField8.setText("");
            jTextField8.setForeground(Color.white); 
        }
    }//GEN-LAST:event_jTextField8FocusGained

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        char ch = evt.getKeyChar();
      if((Character.isISOControl(ch))||(Character.isDigit(ch)&&jTextField7.getText().length()<10)){
          jTextField7.setEditable(true);
      }else{jTextField7.setEditable(false);}
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        char ch = evt.getKeyChar();
      if((Character.isISOControl(ch))||(Character.isDigit(ch)&&jTextField8.getText().length()<6)){
         jTextField8.setEditable(true);
      }else{jTextField8.setEditable(false);}
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        char ch = evt.getKeyChar();
      if(Character.isLetter(ch)||Character.isISOControl(ch)){
          jTextField1.setEditable(true);
      }else{jTextField1.setEditable(false);}
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        char ch = evt.getKeyChar();
      if(Character.isLetter(ch)||Character.isISOControl(ch)||Character.isWhitespace(ch)){
          jTextField2.setEditable(true);
      }else{jTextField2.setEditable(false);}
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        char ch = evt.getKeyChar();
      if(Character.isLetter(ch)||Character.isISOControl(ch)||Character.isWhitespace(ch)){
          jTextField3.setEditable(true);
      }else{jTextField3.setEditable(false);}
    }//GEN-LAST:event_jTextField3KeyPressed

    private void CustomerUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerUIDActionPerformed
       
    }//GEN-LAST:event_CustomerUIDActionPerformed

    private void submitBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtMouseEntered
      submitBt.setBackground(Color.white);
        submitBt.setForeground(new Color(0,51,51));
    }//GEN-LAST:event_submitBtMouseEntered

    private void submitBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtMouseExited
       submitBt.setBackground(new Color(0,51,51));
        submitBt.setForeground(Color.white);
    }//GEN-LAST:event_submitBtMouseExited

    private void nomini_checkBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomini_checkBoxMouseEntered
        jLabel32.setVisible(true);
    }//GEN-LAST:event_nomini_checkBoxMouseEntered

    private void nomini_checkBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomini_checkBoxMouseExited
         jLabel32.setVisible(false);
    }//GEN-LAST:event_nomini_checkBoxMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        System.out.println("I am the Account opaning form my parent is signup Page");
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new accountOpaningForm().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CustomerUID;
    private javax.swing.JRadioButton adminBt;
    private javax.swing.JCheckBox declareBox;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel minimizeL;
    private javax.swing.JCheckBox nomini_checkBox;
    private javax.swing.JFormattedTextField nomini_name;
    private javax.swing.JComboBox<String> nomini_relation;
    private javax.swing.JFormattedTextField nomini_uid;
    private javax.swing.JLabel noteL;
    private javax.swing.JRadioButton publicBt;
    private javax.swing.JButton submitBt;
    // End of variables declaration//GEN-END:variables
}
