/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm_p.BankingPlatform;

import atm_p.DB_Con;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.*;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import splashscreen.LogoIcon;
/**
 *
 * @author user
 */


public class LoginPage extends javax.swing.JFrame {
    PasswordPolicyCheck policy = new PasswordPolicyCheck();
    /**
     * Creates new form Login1
     */
    public LoginPage() {
        initComponents();
         signupPanel.setVisible(false);
          loginPanel.requestFocusInWindow();//If you want to ensure that a particular component gains the focus the first time a window is activated, you can call the requestFocusInWindow method on the component after the component has been realized, but before the frame is displayed. The following sample code shows how this operation can be done:
          setVisible(true);
          new LogoIcon().setLogo(this);
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        loginPanel = new javax.swing.JPanel();
        CustomerIDTF = new javax.swing.JTextField();
        loginpassF = new javax.swing.JPasswordField();
        headingL = new javax.swing.JLabel();
        closeL = new javax.swing.JLabel();
        minimizeL = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HidePswL = new javax.swing.JLabel();
        signupBt = new javax.swing.JButton();
        loginBt = new javax.swing.JButton();
        forgotBt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        loginWarn1 = new javax.swing.JLabel();
        loginWarn2 = new javax.swing.JLabel();
        signupPanel = new javax.swing.JPanel();
        userNameTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        newPassF = new javax.swing.JPasswordField();
        confirmNewPssF = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        createAccountBt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        loginBackLb = new javax.swing.JLabel();
        signupWarn1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        newHidePswL1 = new javax.swing.JLabel();
        conHidePswL2 = new javax.swing.JLabel();
        signupWarn2 = new javax.swing.JLabel();
        signupWarn3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/Background5.jpg"))); // NOI18N

        jPanel1.setOpaque(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/welcomeGif.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setNextFocusableComponent(headingL);

        CustomerIDTF.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        CustomerIDTF.setForeground(new java.awt.Color(204, 204, 204));
        CustomerIDTF.setText("Customer Id Or Admin Id");
        CustomerIDTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        CustomerIDTF.setRequestFocusEnabled(false);
        CustomerIDTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CustomerIDTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CustomerIDTFFocusLost(evt);
            }
        });
        CustomerIDTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerIDTFMouseClicked(evt);
            }
        });

        loginpassF.setForeground(new java.awt.Color(204, 204, 204));
        loginpassF.setText("Enter password");
        loginpassF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        loginpassF.setFocusCycleRoot(true);
        loginpassF.setNextFocusableComponent(loginBt);
        loginpassF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginpassFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginpassFFocusLost(evt);
            }
        });

        headingL.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        headingL.setText("Login");

        closeL.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        closeL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-close-24.png"))); // NOI18N
        closeL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLMouseClicked(evt);
            }
        });

        minimizeL.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        minimizeL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeL.setText("-");
        minimizeL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-user-16.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        HidePswL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-hide-16.png"))); // NOI18N
        HidePswL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        HidePswL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HidePswL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HidePswLMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                HidePswLMouseReleased(evt);
            }
        });

        signupBt.setBackground(new java.awt.Color(0, 0, 0));
        signupBt.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        signupBt.setForeground(new java.awt.Color(255, 255, 255));
        signupBt.setText("Sign Up");
        signupBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupBt.setNextFocusableComponent(signupPanel);
        signupBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupBtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signupBtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signupBtMouseReleased(evt);
            }
        });
        signupBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtActionPerformed(evt);
            }
        });

        loginBt.setBackground(new java.awt.Color(0, 0, 0));
        loginBt.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        loginBt.setForeground(new java.awt.Color(255, 255, 255));
        loginBt.setText("Login");
        loginBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtMouseReleased(evt);
            }
        });
        loginBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtActionPerformed(evt);
            }
        });

        forgotBt.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        forgotBt.setForeground(new java.awt.Color(102, 102, 102));
        forgotBt.setText("Forgot Password?");
        forgotBt.setContentAreaFilled(false);
        forgotBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotBt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        forgotBt.setMargin(new java.awt.Insets(2, 5, 2, 10));
        forgotBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotBtActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-forgot-password-16.png"))); // NOI18N

        loginWarn1.setVisible(false);

        loginWarn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginWarn2.setIconTextGap(10);
        loginWarn2.setVisible(false);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeL, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(closeL, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginBt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(forgotBt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signupBt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(loginpassF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(HidePswL))
                            .addComponent(loginWarn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CustomerIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(jLabel6))
                            .addComponent(headingL, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginWarn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 89, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(minimizeL)
                    .addComponent(closeL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(headingL, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(loginWarn1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginpassF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HidePswL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(loginWarn2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupBt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forgotBt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
        );

        jLayeredPane2.setLayer(loginPanel, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane2.add(loginPanel);
        loginPanel.setBounds(0, 0, 449, 558);

        signupPanel.setBackground(new java.awt.Color(255, 255, 255));

        userNameTf.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        userNameTf.setForeground(new java.awt.Color(204, 204, 204));
        userNameTf.setText("Enter User Name");
        userNameTf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        userNameTf.setCaretPosition(0);
        userNameTf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userNameTf.setDragEnabled(true);
        userNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameTfFocusLost(evt);
            }
        });
        userNameTf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameTfMouseClicked(evt);
            }
        });
        userNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTfActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-user-16.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        newPassF.setForeground(new java.awt.Color(204, 204, 204));
        newPassF.setText("Password");
        newPassF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        newPassF.setEchoChar('\u0000');
        newPassF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newPassFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                newPassFFocusLost(evt);
            }
        });
        newPassF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newPassFKeyTyped(evt);
            }
        });

        confirmNewPssF.setForeground(new java.awt.Color(204, 204, 204));
        confirmNewPssF.setText("Confirm Password");
        confirmNewPssF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        confirmNewPssF.setEchoChar('\u0000');
        confirmNewPssF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmNewPssFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmNewPssFFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Use 8 or more characters with a mix of letters, numbers");
        jLabel5.setToolTipText("");

        createAccountBt.setBackground(new java.awt.Color(0, 0, 0));
        createAccountBt.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        createAccountBt.setForeground(new java.awt.Color(255, 255, 255));
        createAccountBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-create-16.png"))); // NOI18N
        createAccountBt.setText("Create Account");
        createAccountBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccountBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Already a user? ");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        loginBackLb.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        loginBackLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBackLb.setText("LOGIN");
        loginBackLb.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        loginBackLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBackLb.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        loginBackLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBackLbMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("& symbols");
        jLabel8.setToolTipText("");

        newHidePswL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-hide-16.png"))); // NOI18N
        newHidePswL1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        newHidePswL1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newHidePswL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newHidePswL1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newHidePswL1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newHidePswL1MouseReleased(evt);
            }
        });

        conHidePswL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm_p/pictures/icons8-hide-16.png"))); // NOI18N
        conHidePswL2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        conHidePswL2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conHidePswL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conHidePswL2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                conHidePswL2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                conHidePswL2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout signupPanelLayout = new javax.swing.GroupLayout(signupPanel);
        signupPanel.setLayout(signupPanelLayout);
        signupPanelLayout.setHorizontalGroup(
            signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signupWarn3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupWarn1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(signupPanelLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel7))
                    .addComponent(userNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(createAccountBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, signupPanelLayout.createSequentialGroup()
                            .addComponent(newPassF, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(newHidePswL1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, signupPanelLayout.createSequentialGroup()
                            .addComponent(confirmNewPssF, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(conHidePswL2)))
                    .addComponent(signupWarn2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(loginBackLb)
                .addGap(157, 157, 157))
        );
        signupPanelLayout.setVerticalGroup(
            signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(signupWarn1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newPassF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newHidePswL1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(signupWarn2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmNewPssF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conHidePswL2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(signupWarn3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addComponent(createAccountBt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(loginBackLb))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        signupWarn1.setVisible(false);
        signupWarn2.setVisible(false);
        signupWarn3.setVisible(false);

        jLayeredPane2.setLayer(signupPanel, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane2.add(signupPanel);
        signupPanel.setBounds(0, 120, 450, 440);
        signupPanel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(449, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 459, Short.MAX_VALUE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        headingL.setText("Sign Up");
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
       headingL.setText("Login");
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    }//GEN-LAST:event_jButton2MouseClicked

    private void forgotBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotBtActionPerformed

    private void loginBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtMouseReleased
        loginBt.setBackground(Color.black);
        loginBt.setForeground(Color.white);

    }//GEN-LAST:event_loginBtMouseReleased

    private void loginBtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtMousePressed
        loginBt.setBackground(Color.white);
        loginBt.setForeground(Color.black);

    }//GEN-LAST:event_loginBtMousePressed

    private void signupBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBtMouseReleased
        signupBt.setBackground(Color.black);
        signupBt.setForeground(Color.white);
    }//GEN-LAST:event_signupBtMouseReleased

    private void signupBtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBtMousePressed
        signupBt.setBackground(Color.white);
        signupBt.setForeground(Color.black);
        
    }//GEN-LAST:event_signupBtMousePressed

    private void signupBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBtMouseExited
        if(signupBt.isEnabled())headingL.setText("Login");
    }//GEN-LAST:event_signupBtMouseExited

    private void signupBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBtMouseEntered
        if(signupBt.isEnabled())headingL.setText("SignUp");
    }//GEN-LAST:event_signupBtMouseEntered

    private void HidePswLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HidePswLMouseReleased
        loginpassF.setEchoChar('\u2022');
        HidePswL.setIcon(new ImageIcon(getClass().getResource("/atm_p/pictures/icons8-hide-16.png")));
        
    }//GEN-LAST:event_HidePswLMouseReleased

    private void HidePswLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HidePswLMousePressed
        loginpassF.setEchoChar('\u0000');
                HidePswL.setIcon(new ImageIcon(getClass().getResource("/atm_p/pictures/icons8-eye-16.png")));

    }//GEN-LAST:event_HidePswLMousePressed

    private void minimizeLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLMouseClicked
        setState(LoginPage.ICONIFIED);//Minimize the window Iconfied is known as minimization process

    }//GEN-LAST:event_minimizeLMouseClicked

    private void closeLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLMouseClicked
        dispose();
        new atm_p.Main().setVisible(true);

    }//GEN-LAST:event_closeLMouseClicked

    private void signupBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtActionPerformed
     signupPanel.setVisible(true);
     componentEnable(false);
    }//GEN-LAST:event_signupBtActionPerformed

    private void newPassFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPassFFocusGained
        newPassF.setEchoChar('\u2022');
       
        if(!(newPassF.getForeground().equals(Color.black))){
             newPassF.setForeground(Color.black);
            newPassF.setText("");
        }  
        
    }//GEN-LAST:event_newPassFFocusGained

    private void confirmNewPssFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmNewPssFFocusGained
        confirmNewPssF.setEchoChar('\u2022');
        if(!( confirmNewPssF.getForeground().equals(Color.black))){
              confirmNewPssF.setForeground(Color.black);
             confirmNewPssF.setText("");
        }  
    }//GEN-LAST:event_confirmNewPssFFocusGained

    private void loginBackLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBackLbMouseClicked
       signupPanel.setVisible(false);
        componentEnable(true);
        headingL.setText("Login");

    }//GEN-LAST:event_loginBackLbMouseClicked

    private void userNameTfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameTfMouseClicked
       userNameTf.requestFocus();
    }//GEN-LAST:event_userNameTfMouseClicked

    private void CustomerIDTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerIDTFMouseClicked
           CustomerIDTF.requestFocus();
    }//GEN-LAST:event_CustomerIDTFMouseClicked

    private void loginpassFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginpassFFocusGained
        if(!(loginpassF.getForeground().equals(Color.black))){
            loginpassF.setText("");
            loginpassF.setForeground(Color.black); 
        } 
        loginpassF.setEchoChar('\u2022');
    }//GEN-LAST:event_loginpassFFocusGained

    private void CustomerIDTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CustomerIDTFFocusLost
        if(evt.getOppositeComponent()!=null){
            if((evt.getOppositeComponent().equals(loginpassF))|| evt.getOppositeComponent().equals(loginBt)){
                if(CustomerIDTF.getText().isBlank()||!(CustomerIDTF.getForeground().equals(Color.black))){
                    new Warning<>(CustomerIDTF, jLabel6,loginWarn1,"Enter a customer id or an admin id !",false);
                }
                else if(CustomerIDTF.getText().length()<6){
                    new Warning<>(CustomerIDTF, jLabel6,loginWarn1,"Invalid !",false);
                }
                else if(!(CustomerIDTF.getText().substring(0, 2).equals("AS")||CustomerIDTF.getText().substring(0, 3).equals("SAK"))){
                    new Warning<>(CustomerIDTF, jLabel6,loginWarn1,"No such id exist !",true);
                }
                else{new Warning<>().normal(new JComponent[]{CustomerIDTF, jLabel6},loginWarn1);
                
                }
            }
        }
        
    }//GEN-LAST:event_CustomerIDTFFocusLost

    private void loginpassFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginpassFFocusLost
        if(evt.getOppositeComponent()!=null){   
            if((evt.getOppositeComponent().equals(CustomerIDTF))|| evt.getOppositeComponent().equals(loginBt)){
                if(loginpassF.getPassword().length<8 || loginpassF.getForeground()== new Color(204,204,204)){
                     new Warning<>(loginpassF, HidePswL,loginWarn2,"Password is not valid",false);
                }
                else{new Warning<>().normal(new JComponent[]{loginpassF, HidePswL},loginWarn2);
                }
            }    
        
         }
    }//GEN-LAST:event_loginpassFFocusLost

    private void CustomerIDTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CustomerIDTFFocusGained
         CustomerIDTF.requestFocus();
        if(!(CustomerIDTF.getForeground().equals(Color.black))){
            CustomerIDTF.setText("");
            CustomerIDTF.setForeground(Color.black); 
        }   
    }//GEN-LAST:event_CustomerIDTFFocusGained

    private void userNameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTfFocusLost
        if(evt.getOppositeComponent()!=null){
            if((evt.getOppositeComponent().equals(newPassF))|| evt.getOppositeComponent().equals(confirmNewPssF)||evt.getOppositeComponent().equals(createAccountBt)){
                if(userNameTf.getText().isBlank()||!(userNameTf.getForeground().equals(Color.black))){
                    new Warning<>(userNameTf, jLabel7,signupWarn1,"Enter an user name !",false);
                }
                else if(userNameTf.getText().length()<6){
                    new Warning<>(userNameTf, jLabel7,signupWarn1,"User name should be minimum 6 characters !",false);
                }
                else{new Warning<>().normal(new JComponent[]{userNameTf, jLabel7},signupWarn1);
                
                }
            }
        }
    }//GEN-LAST:event_userNameTfFocusLost

    private void userNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTfActionPerformed

    private void userNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTfFocusGained
        userNameTf.requestFocus();
        if(!(userNameTf.getForeground().equals(Color.black))){
            userNameTf.setText("");
            userNameTf.setForeground(Color.black); 
        }  
    }//GEN-LAST:event_userNameTfFocusGained

    private void newPassFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPassFFocusLost
        if(evt.getOppositeComponent()!=null){   
            if((evt.getOppositeComponent().equals(userNameTf))|| evt.getOppositeComponent().equals(confirmNewPssF)||evt.getOppositeComponent().equals(createAccountBt)){
                if(!(newPassF.getForeground().equals(Color.black)) || newPassF.getPassword().length==0){
                    new Warning<>( newPassF,newHidePswL1,signupWarn2,"Please enter password !",false);
                }
                else if( newPassF.getPassword().length<8){
                     new Warning<>( newPassF,newHidePswL1,signupWarn2,"Password must be minimum 8 characters",false);
                }
                else if(!policy.check()){
                    new Warning<>( newPassF,newHidePswL1,signupWarn2,policy.policeBreak(),false);
                }
                else{new Warning<>().normal(new JComponent[]{newPassF,newHidePswL1},signupWarn2);
                }
            }    
        
         }
    }//GEN-LAST:event_newPassFFocusLost

    private void newPassFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPassFKeyTyped
        policy.run(evt.getKeyChar());
    }//GEN-LAST:event_newPassFKeyTyped

    private void confirmNewPssFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmNewPssFFocusLost
        String password= String.valueOf(newPassF.getPassword());
       String conPassword= String.valueOf(confirmNewPssF.getPassword());
        if(evt.getOppositeComponent()!=null){   
            if((evt.getOppositeComponent().equals(userNameTf))|| evt.getOppositeComponent().equals(newPassF)||evt.getOppositeComponent().equals(createAccountBt)){
                if(!(confirmNewPssF.getForeground().equals(Color.black))||newPassF.getPassword().length==0){
                    new Warning<>( confirmNewPssF,conHidePswL2,signupWarn3,"Please enter confirm password !",false);
                }
                else if(!password.equals(conPassword)){
                     new Warning<>( confirmNewPssF,conHidePswL2,signupWarn3,"Password does not match !",false);
                }
                else{new Warning<>().normal(new JComponent[]{confirmNewPssF,conHidePswL2},signupWarn3);
                }
            }    
        
         }
    }//GEN-LAST:event_confirmNewPssFFocusLost

    private void newHidePswL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newHidePswL1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_newHidePswL1MouseClicked

    private void newHidePswL1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newHidePswL1MousePressed
        newPassF.setEchoChar('\u0000');
                HidePswL.setIcon(new ImageIcon(getClass().getResource("/atm_p/pictures/icons8-eye-16.png")));
    }//GEN-LAST:event_newHidePswL1MousePressed

    private void newHidePswL1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newHidePswL1MouseReleased
        newPassF.setEchoChar('\u2022');
                HidePswL.setIcon(new ImageIcon(getClass().getResource("/atm_p/pictures/icons8-Hide-16.png")));
    }//GEN-LAST:event_newHidePswL1MouseReleased

    private void conHidePswL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conHidePswL2MouseClicked
       
    }//GEN-LAST:event_conHidePswL2MouseClicked

    private void conHidePswL2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conHidePswL2MousePressed
         confirmNewPssF.setEchoChar('\u0000');
                HidePswL.setIcon(new ImageIcon(getClass().getResource("/atm_p/pictures/icons8-eye-16.png")));
    }//GEN-LAST:event_conHidePswL2MousePressed

    private void conHidePswL2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conHidePswL2MouseReleased
       confirmNewPssF.setEchoChar('\u2022');
                HidePswL.setIcon(new ImageIcon(getClass().getResource("/atm_p/pictures/icons8-Hide-16.png")));
    }//GEN-LAST:event_conHidePswL2MouseReleased

    private void createAccountBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtActionPerformed
          if(!(signupWarn2.isVisible()||signupWarn1.isVisible()|| signupWarn3.isVisible())){
           if(!(userNameTf.getForeground().equals(Color.black)&& newPassF.getForeground().equals(Color.black)&&confirmNewPssF.getForeground().equals(Color.black))){
               new Warning<>(new JComponent[]{userNameTf,jLabel7,newPassF,newHidePswL1,confirmNewPssF,conHidePswL2}, signupWarn3, "Please fill the details !", true);
           }
           else{
               UserProfileData userProfileData = new UserProfileData();
               userProfileData.UserName=userNameTf.getText();
               userProfileData.Password=String.valueOf(newPassF.getPassword());
               java.awt.EventQueue.invokeLater(new Runnable(){
                   public void run(){                            
                           accountOpaningForm openedForm=new accountOpaningForm(userProfileData);
                           openedForm.openedForm=openedForm;
                           openedForm.setVisible(true);
                            dispose();
                       
                   }
               });
               
           }
       }
       else{
           Toolkit.getDefaultToolkit().beep();
       }
      
        
    }//GEN-LAST:event_createAccountBtActionPerformed

    private void loginBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtActionPerformed
         if(!(loginWarn2.isVisible()||loginWarn1.isVisible())){
           if(!(CustomerIDTF.getForeground().equals(Color.black)&& loginpassF.getForeground().equals(Color.black))){
               new Warning<>(new JComponent[]{CustomerIDTF,jLabel6,loginpassF,HidePswL}, loginWarn2, "Please fill the details !", true);
           }
           else{
                String Id = CustomerIDTF.getText();
                String psw = String.valueOf(loginpassF.getPassword());
                String subC = Id.substring(0, 2);
                String subA=Id.substring(0, 3);
                try{
                    Connection con = DB_Con.getConnection();
                    if(subC.equals("AS")){
                        if(SearchIDInDb(con, "customer", "CID", Id)){
                            if(SearchPswInDb(con, "customer","CID",Id, psw)){
                                ///Welcome Page Entry point For Custoemr
                                new Welcome_user(con,"app.customer","CID",Id).setVisible(true);
                                dispose();
                                
                            }else{
                                new Warning<>(loginpassF, HidePswL,loginWarn2,"Wrong password !",true);
                            }
                        }
                        else{ new Warning<>(CustomerIDTF, jLabel6,loginWarn1,"Wrong Customer id !",true);}
                    }
                    else if(subA.equals("SAK")){
                        if(SearchIDInDb(con, "admininfo", "AID", Id)){
                            if(SearchPswInDb(con, "admininfo","AID",Id, psw)){
                               new Welcome_user(con,"app.admininfo","AID",Id).setVisible(true);
                               ///Welcome Page Entry point For Admin
                               dispose();
                            }else{
                                new Warning<>(loginpassF, HidePswL,loginWarn2,"Wrong password !",true);
                            }
                        }
                        else{ new Warning<>(CustomerIDTF, jLabel6,loginWarn1,"Wrong Admin id !",true);}
                        
                    }
                }catch(Exception e){
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "unable to connect DATABASE","Error",JOptionPane.INFORMATION_MESSAGE,new ImageIcon(getClass().getResource("/atm_p/pictures/icons8-error.png")));

                }
           }
       }
       else{
           Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_loginBtActionPerformed
    Timer tm;
    private void disposeFun(int millisecond,JFrame obj){
        tm = new Timer(millisecond,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                obj.dispose();
                tm.stop();
            }
        });
        tm.start();
    }
    
    private boolean SearchIDInDb(Connection con,String Table,String idColumn,String ID)throws Exception{

        PreparedStatement pstmt = con.prepareStatement("select "+idColumn+" from "+"app."+Table+" where "+idColumn+" = ? ");
        pstmt.setString(1, ID);
        return pstmt.executeQuery().next();
    }
   
   private boolean SearchPswInDb(Connection con,String Table,String idColumn,String ID,String psw)throws Exception{
        PreparedStatement pstmt = con.prepareStatement("select "+idColumn+",Password from "+"app."+Table+" where "+idColumn+" = ? AND Password = ?");
        pstmt.setString(1, ID);
        pstmt.setString(2, psw);
        if(pstmt.executeQuery().next()){
            return true;            
        }
        return false;
   }     
    private void componentEnable(boolean bool){
        loginBt.setEnabled(bool);
        signupBt.setEnabled(bool);
        forgotBt.setEnabled(bool);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       FlatLightLaf.setup();
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new LoginPage();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustomerIDTF;
    private javax.swing.JLabel HidePswL;
    private javax.swing.JLabel closeL;
    private javax.swing.JLabel conHidePswL2;
    private javax.swing.JPasswordField confirmNewPssF;
    private javax.swing.JButton createAccountBt;
    private javax.swing.JButton forgotBt;
    private javax.swing.JLabel headingL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginBackLb;
    private javax.swing.JButton loginBt;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginWarn1;
    private javax.swing.JLabel loginWarn2;
    private javax.swing.JPasswordField loginpassF;
    private javax.swing.JLabel minimizeL;
    private javax.swing.JLabel newHidePswL1;
    private javax.swing.JPasswordField newPassF;
    private javax.swing.JButton signupBt;
    private javax.swing.JPanel signupPanel;
    private javax.swing.JLabel signupWarn1;
    private javax.swing.JLabel signupWarn2;
    private javax.swing.JLabel signupWarn3;
    private javax.swing.JTextField userNameTf;
    // End of variables declaration//GEN-END:variables
}
